openapi: 3.1.0
info:
  title: Engine Mode Controller
  version: 1.0.0
  description: Set precision level, compact mode, or failsafe processing modes.
servers:
  - url: https://yourusername.github.io/rtc-engine-gpt
paths:
  /set-mode:
    post:
      operationId: setEngineMode
      summary: Set engine to compact, full, failsafe, or precision mode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mode:
                  type: string
                  enum: [full, compact, failsafe, precision]
      responses:
        '200':
          description: Engine mode set successfully
  /get-mode:
    get:
      operationId: getEngineMode
      summary: Get current engine processing mode
      responses:
        '200':
          description: Current mode returned
